### PR TITLE
upgrade to minecraft 1.9

### PR DESCRIPTION
**Pull request by JacobKorn**
small tweak to get the build tools to compile 1.9

### CODE REVIEW

**Comment by ruippeixotog** [comment]
Hi @JacobKorn, thanks for the pull request! I did some changes in master to better support multiple versions; in particular, I extracted the revision to an environment variable and created some tags so that old images are preserved (e.g. as `ruippeixotog/spigot:1.8.3`). Can you update your pull request to fix the merge conflicts?

On another note, why did you remove the `--noconsole` argument? In an Ubuntu host, I experienced a 100% CPU usage when running it as a daemon when `--noconsole` is activated. I guess it's some busy waiting for input in the absence of a TTY.

**Comment by ruippeixotog** [comment]
@JacobKorn, I have just updated it myself to 1.9, as I needed to make that version available from Docker Hub. From now on you should be able to docker pull either the `1.9` tag for Minecraft 1.9 or the default `latest` tag for the latest Minecraft version. Thank you for pointing out the version argument to `BuildTools.jar`!

**Comment by JacobKorn** [comment]
Hi @ruippeixotog. Sorry, I just saw this now I must have missed the reply notifications.

I'm still just learning about docker and running servers, so thank you for the explanation of what you did, it's hugely helpful. 

In terms of removing `--noconsole`, I can't quite remember why I removed that. I think I wanted to see the output as it was happening while I was working things out and didn't see a reason not show it. I don't think I experienced the 100% CPU though.

I'm just upgrading to 1.10.2 now. Should I be be creating another pull request with `SPIGOT_REV` set to `1.10.2` and a `1.10.2` tag or will `docker pull ruippeixotog/spigot:latest` just work? If so, how does that work?

What do you think about using a build arg eg `ARG SPIGOT_REV` then building with `docker build --build-arg SPIGOT_REV=1.10.2`

**Comment by JacobKorn** [comment]
for now I just changed `SPIGOT_REV` to `latest` in my local Dockerfile which builds the latest version.

**Comment by ruippeixotog** [comment]
Hi @JacobKorn! Build args are a recent feature, I didn't know of their existence until now. This repo is using Docker Cloud automated builds: every time a new commit is pushed to master, the image is built with the `latest` tag and pushed to the Docker registry. In order to create version-locked tags I used to create Git tags in order to make Docker Cloud build them automatically. But with build args I prefer to have `ARG SPIGOT_REV=latest` in the Dockerfile, to keep the latest tag automatic and to build manually concrete version-locked tags as needed.

Can you make a pull request converting the `ENV` command into an `ARG` one with the default as `latest`?

**Comment by JacobKorn** [comment]
Ok, that sounds good. Yes I can do a pull request for that.

**Pull request closed without merging**
